language: node_js
node_js:
- '6'

sudo: required

services:
  - docker

after_success:
  - docker build -t rmitra/rapido-authentication:1.0 .
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push rmitra/rapido-authentication